module: CredentialsJWT
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-CredentialsJWT/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-CredentialsJWT.xcodeproj, -target, CredentialsJWT, LIBRARY_SEARCH_PATHS=.build/debug]

