module: CredentialsJWT
author: IBM and the Kitura project contributors
github_url: https://github.com/Kitura/Kitura-CredentialsJWT/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

